# Generated by Django 3.2.14 on 2022-07-25 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='desription',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='district',
            field=models.CharField(choices=[('Amudaryo tumani', 'Amudaryo tumani'), ('Beruniy tumani', 'Beruniy tumani'), ('Kegayli tumani', 'Kegayli tumani'), ('Qonliko‘l tumani', 'Qonliko‘l tumani'), ('Qorao‘zak tumani', 'Qorao‘zak tumani'), ('Qo‘ng‘irot tumani', 'Qo‘ng‘irot tumani'), ('Mo‘ynoq tumani', 'Mo‘ynoq tumani'), ('Nukus tumani', 'Nukus tumani'), ('Nukus shahri', 'Nukus shahri'), ('Taxtako‘pir tumani', 'Taxtako‘pir tumani'), ('To‘rtko‘l tumani', 'To‘rtko‘l tumani'), ('Xo‘jayli tumani', 'Xo‘jayli tumani'), ('Chimboy tumani', 'Chimboy tumani'), ('Shumanay tumani', 'Shumanay tumani'), ('Ellikqal‘a tumani', 'Ellikqal‘a tumani'), ('Taxiatosh shahri', 'Taxiatosh shahri'), ('Bo‘zatov tumani', 'Bo‘zatov tumani')], default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='file',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='innovastion_part',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='project_aim',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='region',
            field=models.CharField(choices=[('Qoraqalpog‘iston Respublikasi', 'Qoraqalpog‘iston Respublikasi'), ('Andijon viloyati', 'Andijon viloyati'), ('Buxoro viloyati', 'Buxoro viloyati'), ('Jizzax viloyati', 'Jizzax viloyati'), ('Qashqadaryo viloyati', 'Qashqadaryo viloyati'), ('Navoiy viloyati', 'Navoiy viloyati'), ('Namangan viloyati', 'Namangan viloyati'), ('Samarqand viloyati', 'Samarqand viloyati'), ('Surxandaryo viloyati', 'Surxandaryo viloyati'), ('Sirdaryo viloyati', 'Sirdaryo viloyati'), ('Toshkent viloyati', 'Toshkent viloyati'), ('Farg‘ona viloyati', 'Farg‘ona viloyati'), ('Xorazm viloyati', 'Xorazm viloyati'), ('Toshkent shahri', 'Toshkent shahri')], default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.category'),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='person_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.person'),
        ),
        migrations.AlterField(
            model_name='project',
            name='price',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(null=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.project')),
            ],
        ),
    ]
