# Generated by Django 3.2.14 on 2022-07-25 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220725_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='created_at',
        ),
    ]
